#!/usr/bin/sh

[ "$CXX" ] || CXX="g++"
CXXFLAGS="-Wall -Wextra -std=c++20 -O3 -Ishared"

standalone="ls uniq"
with_for_each_file="cat"

noisy() {
	echo "$@"
	$@
}

case $1 in
	clean)
		noisy rm -f $standalone
		noisy rm -f $with_for_each_file
		exit
		;;
esac

for prog in $standalone; do
	if [ "$prog"".cc" -nt "$prog" ]; then
		noisy $CXX $CXXFLAGS -o "$prog" "$prog"".cc"
	fi
done

for prog in $with_for_each_file; do
	if [ "$prog"".cc" -nt "$prog" ]; then
		noisy $CXX $CXXFLAGS -o "$prog" "$prog"".cc" "shared/for_file.cc"
	fi
done
